baseURL = 'https://aattentionn.github.io/cv-site/'
languageCode = 'en-us'
title = 'Анна Никешина'
theme = "cv-theme"

[menu]

  [[menu.main]]
    identifier = "first"
    name = "First"
    url = "/first/"
    weight = 10

  [[menu.main]]
    identifier = "second"
    name = "Second"
    url = "/second/"
    weight = 20