baseURL = 'https://aattentionn.github.io/cv-site/'
languageCode = 'en-us'
title = 'Анна Никешина'
theme = "cv-theme"

[menu]

  [[menu.main]]
    identifier = "first"
    name = "First"
    url = "/pages/first/"
    weight = 10

  [[menu.main]]
    identifier = "second"
    name = "Second"
    url = "/pages/second/"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "Контакты"
    url = "/contact/"
    weight = 30